# mailer queue settings
queue_url: https://sqs.us-east-1.amazonaws.com/172327596604/custodian-mailer-queue
role: arn:aws:iam::172327596604:role/CloudCustodian-ExecutionRole
region: us-east-1

# lambda function settings
lambda_tags:
  contact: devops@optum.com
  environment: central
  repo: cloud-custodian
runtime: python3.11

# custom-defined contact tags for email notify
contact_tags:
  - contact
  - owner

# sender address for email notify
from_address: ysrinu95@gmail.com